### ISSUE TITLE
it may be converted to an ES6 module.ts

### ISSUE THREAD

**Issue by ykws** [ykws/hello-node#1]
```index.js
var require: NodeRequire
(id: string) => any
File is a CommonJS module; it may be converted to an ES6 module.ts(80001)
```

**Comment by ykws** [comment]
Quick Fix, and run `node index.js`, SyntaxError: Unexpected token **import**

```index.js
$ node index.js
/Users/ykws/Workspace/Github/ykws/hello-node/index.js:1
(function (exports, require, module, __filename, __dirname) { import { createServer } from 'http';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
```

**Comment by ykws** [comment]
```
$ npm i esm
$ node -r esm index.js
```

Successful 👍 

https://stackoverflow.com/questions/47277887/node-experimental-modules-requested-module-does-not-provide-an-export-named
